# Generated by Django 4.2.5 on 2023-09-05 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftySymbol',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_order_sleep_secs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tele_api_id', models.PositiveIntegerField()),
                ('tele_api_hash', models.CharField(max_length=255)),
                ('tele_sleep_secs', models.PositiveIntegerField(default=10)),
                ('tele_peer_channel_id', models.BigIntegerField()),
                ('tele_msg_limit', models.PositiveIntegerField(default=5)),
                ('tele_last_message_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signal_datetime', models.DateTimeField(auto_now_add=True)),
                ('strike_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol_token', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('nifty_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.niftysymbol')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TraderSecret',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angel_client_id', models.CharField(max_length=255)),
                ('angel_client_pin', models.CharField(max_length=255)),
                ('angel_api_key', models.CharField(max_length=255)),
                ('angel_qr_code_token', models.CharField(max_length=255)),
                ('jwtToken', models.TextField(blank=True, default=None, null=True)),
                ('refreshToken', models.TextField(blank=True, default=None, null=True)),
                ('feedToken', models.TextField(blank=True, default=None, null=True)),
                ('trade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.trader')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strike_symbol', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_order_id', models.CharField(max_length=255)),
                ('exit_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nifty_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.niftysymbol')),
                ('trade_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.tradesignal')),
                ('trade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.trader')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nifty_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.niftysymbol')),
            ],
        ),
        migrations.CreateModel(
            name='StopLoss',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nifty_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.niftysymbol')),
            ],
        ),
    ]
