# Generated by Django 4.2.5 on 2023-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intellitrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='sl_to_entry',
            field=models.BooleanField(default=False),
        ),
    ]
