# Generated by Django 4.2.5 on 2023-09-12 10:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Intellitrade', '0002_tradesignal_sl_to_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='exit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DayWiseStrike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('nifty_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intellitrade.niftysymbol')),
            ],
        ),
    ]
