# Generated by Django 4.2.5 on 2023-09-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intellitrade', '0003_tradesignal_exit_datetime_tradesignal_exit_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daywisestrike',
            unique_together={('nifty_symbol', 'week_day')},
        ),
    ]
